[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP", "B", "PL"]
ignore = ["B008"]

[tool.pytest.ini_options]
addopts = "-q --disable-warnings"
testpaths = ["backend/tests"]
